
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBmv1pg","is_bot":false,"login":"livjono","name":"Olivia Jonokuchi"},"headRefName":"Liv-READMEFixes","number":30,"title":"Update README.md","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-3/pull/30"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-homecontroller","number":29,"title":"Changed Home Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-3/pull/29"}]
