
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBqGjHg","is_bot":false,"login":"madisonlong1","name":""},"headRefName":"Madison-LocationQueryService","number":24,"title":"Madison location query service","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-3/pull/24"},{"author":{"id":"MDQ6VXNlcjI2Mjg4OTA4","is_bot":false,"login":"kellyyan","name":"Kelly Yan"},"headRefName":"Kelly-PublicHoliday-Controller","number":23,"title":"Add PublicHoliday Service and Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-3/pull/23"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-jokes-controller","number":19,"title":"Add Joke Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-3/pull/19"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-jokesservice","number":18,"title":"Added Joke Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-3/pull/18"}]
